controller_list:
  - name: fake_spot_arm_controller
    type: $(arg execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - Joint6
      - Joint7
initial:  # Define initial robot poses.
  - group: spot_arm
    pose: Zero
  - group: hand
    pose: close
